sudo: required
services:
  - docker

before-install:
  - docker pull node:8-onbuild

install:
  - docker build -t probot-hello .

script:
  - docker run --rm probot-hello npm run test
  - docker run --rm probot-hello npm run lint

after-sucess:
  - docker tag probot-hello probot-hello:$(git rev-parse HEAD)
